sudo: required
dist: trusty
language: fortran

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: clang
      env: BTYPE=Debug
    - os: linux
      compiler: gcc
      env: BTYPE=Release

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gfortran; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install liblapack-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install fftw3; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libfftw3-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python; fi

install:
  - mkdir pscf-build && cd pscf-build
  # Configure
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_Fortran_COMPILER=`which gfortran` -DCMAKE_BUILD_TYPE=$BTYPE -DCMAKE_INSTALL_PREFIX=~/pscf
  # Build
  - make

script:
  ## Test the program
  #- make test
  # Create package
  - make package
  # Make sure we can install with no issues.
  - make install
